### ISSUE TITLE
Unable to remove packages (windows)

### ISSUE THREAD

**Issue by tbnguyen1407** [candrewlee14/webman#12]
## Version
v0.5.0

## Problem
Unable to remove package after installing on windows

![webman-remove-error](https://user-images.githubusercontent.com/2490928/168464447-8ef34aa3-5f98-4925-b1de-74b7632577de.png)

**Comment by candrewlee14** [comment]
Thanks for catching this. I'm going to be adding better testing soon to make sure commits don't break any commands, so that'll help stabilize things.
