### ISSUE TITLE
Add gitea-release strategy

### ISSUE THREAD

**Issue by jolheiser** [candrewlee14/webman#23]
This would also require a base URL for a given Gitea instance. 

This may tie into #17 as well, since I'd imagine it would potentially get messy to add pkgs from various Gitea instances to the main pkg repo.

**Comment by candrewlee14** [comment]
Good idea. How about if we add a parameter for the git release strategy that defaults to github?

**Comment by jolheiser** [comment]
Do you think the release-strategy being called `github-release` will be confusing?

Do we want to rename it `git-release`?
Or some other alternative?

**Comment by candrewlee14** [comment]
We should probably rename. Git-release seems fine to me 👍

**Comment by jolheiser** [comment]
I'll throw together a PR later. 🚀

**Comment by jolheiser** [comment]
> Good idea. How about if we add a release url base parameter for the git release strategy that defaults to github?

As another aside, this will also work for people self hosting GH, so a few birds with one stone. 💯

**Comment by jolheiser** [comment]
Do you want to leave `github-release` as a "legacy" thing to avoid changing all recipes, or change it wholesale?

**Comment by candrewlee14** [comment]
Actually, yeah, I think you're right to just add a new gitea strategy. It's an easy enough change, both for the schema and in code.

Right now I can't think of a way to keep all the custom release info in the recipes, but if there's a good way of doing that easily (with a base url and response schema maybe?), that could be better. Let me know if you have any ideas.

**Comment by jolheiser** [comment]
I've made #24 for this issue, but as an aside for GH self-hosted instances, we could also add `github_url` to the schema (defaulting to `https://github.com`) which would allow for self-hosted GH instances without breaking any existing recipes.
