### ISSUE TITLE
Output broken on Windows

### ISSUE THREAD

**Issue by enr** [candrewlee14/webman#54]
Hi @candrewlee14 ,
thank you for this project.

I have an ugly output on a Windows cmd shell (note: other apps output is managed well, even when using colors or other ANSI escape codes)

![webman](https://user-images.githubusercontent.com/150710/194281187-fb152de7-8f09-4f7a-9da5-64311564727d.png)

The best option would be fix this behaviour, but imho it is acceptable to allow user to disable the colored output.
Cheers, Enrico

**Comment by jolheiser** [comment]
Windows terminal was able to fix it for me.

On win10, both cmd and powershell cannot correctly display the codes used to move the cursor, which leads to this.

**Comment by candrewlee14** [comment]
What do you think about using https://github.com/mattn/go-isatty to identify whether color should be used or not as well?

**Comment by candrewlee14** [comment]
Merged in #55
